#+Allegro (excl::set-case-mode :case-sensitive-lower)
(load "mma")
(use-package :mma)
#+Allegro (load "hcons")
#+Allegro (load "ucons1")
#-Allegro (load "uconsalt")
(load "parser")
(load "stack1")
(load "disp1")
#+Allegro (load "eval")
#-Allegro (load "eval2")
(load "poly")
(load "rat1")
(load "simp1")
(load "pf")
(load "match")
(load "diffrat")
